#!/bin/bash

set -e
set -x

mv /usr/sbin/policy-rc.d.disabled /usr/sbin/policy-rc.d
apt-get update
apt-get -y --no-install-recommends install emacs-nox yaml-mode git-core
apt-get -y -u dist-upgrade
apt-get clean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
/usr/local/bin/docker-wipelogs
mv /usr/sbin/policy-rc.d /usr/sbin/policy-rc.d.disabled

pip3 install /usr/src/app

adduser --uid 2020 --disabled-password --gecos "Home Assistant" hass

cp -a /usr/local/debian-base-setup/files/init.d-hass-daemon /etc/init.d/hass-daemon
update-rc.d hass-daemon defaults

/etc/init.d/hass-daemon install

