#!/bin/bash

set -e
set -x

pip3 install /usr/src/app

adduser --uid 2020 --disabled-password --gecos "Home Assistant" hass

cp -a /usr/local/debian-base-setup/files/init.d-hass-daemon /etc/init.d/hass-daemon
update-rc.d hass-daemon defaults

/etc/init.d/hass-daemon install

